### ISSUE TITLE
报错了，麻烦帮忙看下  font_text = selector.xpath('//style[@id="js-nuwa"]/text()') 获取到的好像是空列表

### ISSUE THREAD

**Issue by 123wuyu** [zhio/KNN_Font#1]
Traceback (most recent call last):
  File "C:/Users/admin/Desktop/KNN_Font-master/main.py", line 75, in <module>
    response = font_replace(html)
  File "C:/Users/admin/Desktop/KNN_Font-master/main.py", line 46, in font_replace
    base_list = base_font.getGlyphOrder()[2:]    # 取出0-9数字对应的编码列表
AttributeError: 'str' object has no attribute 'getGlyphOrder'
debug了一下，问题出现在
font_text = selector.xpath('//style[@id="js-nuwa"]/text()') 
获取到的好像是空列表

**Comment by zhio** [comment]
这段就是获取它的字体文件，如果没有获取到 可以对照网站源代码 看看。
